name: ⭐️ Demo Action ⭐️

on: push

# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   issue-setup:
      name: setup
      uses: ./.github/workflows/issue-setup.yml

   # prepare-environment:
   #    needs: retrieve-infos
   #    uses: ./.github/workflow/setup-env.yml

   # evaluate-code:
   #    needs: prepare-environment
   #    uses: ./.github/workflow/issue-evaluation.yml
   
   # execute-code:
   #    needs: evaluate-code
   #    uses: ./.github/workflow/execute-code.yaml
   
   # clean-up:
   #    needs: execute-code
   #    uses: ./.github/workflow/clean-up.yaml
   



