name: ⭐️ Demo Action ⭐️

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
   issues:
      types: [opened]

# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   
   setup:
      name: setup
      if: github.actor == 'alefesta'
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: add Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
        run: |
          gh issue edit ${{github.event.issue.number}} --add-label 'in Progress'
      - uses: actions/checkout@v2
      # - name: retrieve
      #    id: infos
      #    uses: alefesta/ermes/.github/workflows/issue-setup.yml@main


   prepare:
      name: prepare
      needs: setup
      if: github.actor == 'alefesta'
      uses: ./.github/workflows/issues-setup.yml
   
   
   execute:
      name: execute code
      if: always()
      needs: prepare
      runs-on: ubuntu-latest
      steps:
         - name: execute
           if: needs.evaluate.result == 'success'
           run:  echo 'done'
         - name: catch-error
           if: needs.evaluate.result == 'failure'
           uses: ./.github/workflows/catch-errors.yml


   catch-errors:
      name: final comments
      needs: [setup,prepare,execute]
      runs-on: ubuntu-latest

      steps:
        - name: sync
          uses: actions/checkout@v2
        - name: evaluate
          if: success()
          env:
            GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
          run: |
           gh run view ${{github.run_id}} > results.txt
           gh issue comment ${{github.event.issue.number}} -F results.txt
           gh issue edit ${{github.event.issue.number}} --add-label done 
           gh issue edit ${{github.event.issue.number}} --remove-label 'in Progress' 
           gh issue edit ${{github.event.issue.number}} --title "✅ ${{ github.event.issue.title }} - Run Completed "
        - name: catch-error
          if: failure()
          env:
            GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
          run: |
           gh run view ${{github.run_id}} --exit-status > error.txt
           gh issue comment ${{github.event.issue.number}} -F error.txt
           gh issue edit ${{github.event.issue.number}} --add-label invalid 
           gh issue edit ${{github.event.issue.number}} --remove-label 'in Progress' 
           gh issue edit ${{github.event.issue.number}} --title "⚠️ ${{ github.event.issue.title }} - Invalid run "
   
   



