name: ⭐️ Demo Action ⭐️

on: push

# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   issue-setup:
      name: setup
      if: github.ref == 'main'
      uses: ./.github/workflows/issue-setup.yml

   prepare-environment:
      needs: issue-setup
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml

   evaluate-code:
      needs: prepare-environment
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml
   
   execute-code:
      needs: evaluate-code
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml
   
   clean-up:
      needs: execute-code
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml
   



