name: ⭐️ Demo Action ⭐️

on: push

# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   issue-setup:
      name: setup
      if: github.ref == 'main'
      uses: ./.github/workflows/issue-setup.yml

   prepare-environment:
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml

   evaluate-code:
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml
   
   execute-code:
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml
   
   clean-up:
      if: github.ref != 'main'
      uses: ./.github/workflows/issue-setup.yml
   



