name: ⭐️ Demo Action ⭐️

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
   issues:
      types: [opened]

# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   
   setup:
      name: setup
      if: github.actor == 'alefesta'
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: add Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
        run: |
          gh issue edit ${{github.event.issue.number}} --add-label 'in Progress'
      - uses: actions/checkout@v2
      # - name: retrieve
      #    id: infos
      #    uses: alefesta/ermes/.github/workflows/issue-setup.yml@main


   prepare:
      name: prepare
      if: github.actor == 'alefesta'
      uses: ./.github/workflows/issue-setup.yml
   
   
   execute:
      name: execute code
      needs: prepare
      runs-on: ubuntu-latest
      steps:
         - name: execute
           if: needs.evaluate.result == 'success'
           run:  echo 'done'
         - name: catch-error
           if: needs.evaluate.result == 'failure'
           uses: ./.github/workflows/issue-setup.yml


   catch-errors:
      name: final comments
      if: always()
      uses: ./.github/workflows/catch-errors.yml
   
   



