name: ⭐️ Demo Action ⭐️

on: push

# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   
   issue-setup:
      name: setup
      if: github.actor == 'alefesta'
      uses: ./.github/workflows/issue-setup.yml

   prepare-environment:
      name: prepare environment
      needs: issue-setup
      if: github.actor != 'alefesta'
      uses: ./.github/workflows/issue-setup.yml

   evaluate-code:
      name: evaluate code to be run
      needs: issue-setup
      if: github.actor != 'alefesta'
      uses: ./.github/workflows/issue-setup.yml
   
   execute-code:
      name: execute code
      needs: [evaluate-code]
      if: github.actor != 'alefesta'
      uses: ./.github/workflows/issue-setup.yml
   
   catch-errors:
      name: catch errors
      if: jobs.evaluate-code.status != 'success' || jobs.execute-code.status != 'success'
      uses: ./.github/workflows/issue-setup.yml
   



