name: ⭐️ Demo Action ⭐️

on: push

# concurrency:
#   group: ci-tests-${{ github.ref }}-1
#   # New commit on branch cancels running workflows of the same branch
#   cancel-in-progress: true

jobs:
   
   issue-setup:
      name: setup
      if: github.actor == 'alefesta'
      uses: ./.github/workflows/issue-setup.yml

   prepare-environment:
      needs: issue-setup
      if: github.actor != 'alefesta'
      uses: ./.github/workflows/issue-setup.yml

   evaluate-code:
      needs: issue-setup
      if: github.actor != 'alefesta'
      uses: ./.github/workflows/issue-setup.yml
   
   # execute-code:
   #    needs: [prepare-environment,evaluate-code]
   #    if: github.actor != 'alefesta'
   #    uses: ./.github/workflows/issue-setup.yml
   
   # clean-up:
   #    needs: [prepare-environment,evaluate-code]
   #    if: github.actor != 'alefesta'
   #    uses: ./.github/workflows/issue-setup.yml
   



