on:
  workflow_run:
    workflows: [Main]
    types: [completed]
env: 
  BRANCH: ${{github.actor}}
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Init
        run: echo 'The triggering workflow passed at $BRANCH'
      - name: Sync
        uses: actions/checkout@v2
      - run: git checkout $BRANCH
      - name: executor
        uses: ./.github/actions/action.yaml
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'