on:
  workflow_run:
    workflows: [Main]
    types: [completed]
env: 
  BRANCH: ${{github.actor}}
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - uses: ./.github/actions/action.yaml@$BRANCH
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'