name: "Retrieve Execution Infos"

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    name: get-infos
    steps:
        - name: Read and Evaluate Inputs
          run: |
            echo "reading input"
            console.log('this is a test')


        - name: Load Json
          shell: bash
          # if: ${{ matrix.os == 'windows-latest' }}
          run: python --version