name: "Retrieve Execution Infos"

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    name: get-infos
    steps:
      - uses: actions/checkout@v2
      - name: Set selected color
        run: echo ('\u001b[32mHello Green\u001b[0m')
