name: "Retrieve Execution Infos"

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    name: get-infos
    steps:
      - uses: actions/checkout@v2
      - name: add Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
        run: |
          gh auth login --with-token $GITHUB_TOKEN
          gh issue edit ${{github.event.issue.number}} --add-label 'in Progress'
      - name: Set selected color
        if: github.actor == 'dummy'
        run: echo -e "\e[31mRed Text\e[0m"
      - name: Set selected color
        if: github.actor == 'duck'
        run: echo -e "\e[31mRed Text\e[0m"
      - name: Set selected color
        if: github.actor == 'alefesta'
        run: echo -e "\e[32;1mBold Light green Text\e[0m"
      
