name: "Retrieve Execution Infos"

on:
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    steps:
        - name: Read and Evaluate Inputs
          run: |
            echo "reading input"
            console.log("this is a test")


        - name: Load Json
          shell: bash
          # if: ${{ matrix.os == 'windows-latest' }}
          run: python --version