name: test

on: [push]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:  
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p test

      - run: echo hello > test/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test/world.txt
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: test
