name: test

on: [push]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:  
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup Infrastructure
        uses: actions/checkout@v2
      - run: |
          mkdir -p test
          echo hello > test/world.txt
      - name: Save Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: test/world.txt
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: results
          path: test
