name: test

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:  
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        with:
          branch: 'release-notes'
