name: Ermes

on:
  issues:
    types: [opened]

jobs:
  Set-Up-Actions:
    runs-on: ubuntu-latest
    # container: docker.io/hello-world
    steps:
      - name: Commit files # transfer the new html files back into the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_WORKFLOW }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b ${{github.actor}}
          cd .github/workflows && curl -O https://raw.githubusercontent.com/alefesta/ermes/main/test.yaml
          git add .
          git commit -m "generated"
          git push --set-upstream origin ${{github.actor}}

      - name: Execute
        uses: actions/checkout@v2
      - run: echo "Starting execution..."
