name: test

on: [push]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    env:  
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        with:
          branch: 'release-notes'
      - uses: DamianReeves/write-file-action@master
        with:
          path: alefesta/ermes/test.txt@release_notes
          contents: |
            echo "Hello World!"
          write-mode: append
